#compose.yaml

services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=chmury"
      - "POSTGRES_USER=admin"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - chmury-network

  app:
    build:
      context: .
    environment:
      - DB_IP=postgres
      - DB_PORT=5432
      - DB_NAME=chmury
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - chmury-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  chmury-network: